#pragma once

#include <cstdint>
#include <string>
#include <vector>

#include "effects.h"
#include "text.h"
#include "transitions.h"

namespace fc {

// One placed media segment on the timeline. Source frames [sourceIn,
// sourceOut) play at timeline position [timelineStart, timelineStart +
// duration) where duration = (sourceOut - sourceIn) / rate.
struct Clip {
    int64_t id = 0;
    std::string sourcePath;
    std::string label;
    int64_t sourceInFrames = 0;  // in-point in the source (inclusive)
    int64_t sourceOutFrames = 0; // out-point in the source (exclusive)
    int64_t timelineStart = 0;   // position on the timeline (frames)
    double rate = 1.0;           // playback rate (1.0 = normal)
    int trackIndex = 0;

    // M5 Phase 1: per-clip effect stack, applied top-to-bottom when the
    // program monitor displays a frame of this clip. Value type: copied
    // with the clip (splitting a clip copies the stack to BOTH halves).
    std::vector<EffectInstance> effectStack;

    // M6 Phase 1: text/title clips. A text clip has NO source (sourcePath
    // empty, sourceInFrames always 0, sourceOutFrames == durationFrames,
    // rate 1.0) - its frames are GENERATED by rendering `text` over the
    // program frame. Text clips live on text tracks (Track::isText); the
    // M4b mutators keep all invariants (the text special-cases are:
    // trim-start and roll adjust sourceOut instead of sourceIn so the
    // head can extend freely, and split keeps the right half's sourceIn
    // at 0). Value type: the document copies with the clip (both halves
    // of a split keep showing the same text).
    bool isText = false;
    TextDocument text;

    int64_t durationFrames() const;
    int64_t timelineEnd() const { return timelineStart + durationFrames(); }
};

struct Track {
    int index = 0;
    std::string name;
    bool isAudio = false;
    // M6 Phase 1: text/title lanes. Video and audio clips cannot move to
    // them and text clips cannot leave them; the program monitor renders
    // text tracks ON TOP of the video stack (see textClipsAt for the
    // paint order). Mutually exclusive with isAudio.
    bool isText = false;
    bool locked = false;
    bool muted = false;
    bool solo = false;
};

// M5 Phase 2: one transition placed on the shared boundary of two ADJACENT
// clips (left.timelineEnd() == right.timelineStart(), same video track).
//
// Window semantics (frame-accurate, zero overlap, zero reflow):
//   * The transition window is the LAST durationFrames frames of the LEFT
//     clip: [boundary - duration, boundary) where boundary = left end.
//   * During the window the outgoing (left) clip keeps playing LIVE at its
//     natural mapping; the incoming (right) clip is PRE-ROLLED as a HELD
//     image of its first source frame (sourceIn). At the cut the right
//     clip plays from its true in-point - no content is skipped, frozen
//     after the cut, or lost, and no clip extent ever moves.
//   * Constraints: 1 <= duration <= left.durationFrames(). Chains are free
//     (W->X and X->Y coexist: their windows live in W's and X's tails).
struct Transition {
    int64_t id = 0;
    int trackIndex = 0;
    int64_t leftClipId = 0;  // the clip whose END is the cut
    int64_t rightClipId = 0; // the clip whose START is the cut
    std::string kind;        // transitions.h catalog id ("dissolve.cross")
    int64_t durationFrames = 0;
};

// One resolvable sample of a transition at a timeline frame (what the
// cross-clip compositor renders: blend frame A at leftSourceFrame with the
// held frame B at rightSourceFrame, at `progress`).
struct TransitionSample {
    int64_t transitionId = 0;
    int trackIndex = 0;
    std::string kind;
    int64_t leftClipId = 0;
    int64_t rightClipId = 0;
    int64_t windowStartFrame = 0; // inclusive
    int64_t windowEndFrame = 0;   // exclusive: the cut == left clip end
    int64_t leftSourceFrame = 0;  // the outgoing clip's LIVE source position
    int64_t rightSourceFrame = 0; // the incoming clip's HELD first frame
    double progress = 0.0;        // (frame - windowStart) / duration, [0, 1)
};

// Frame-accurate timeline model (Module 6.2 / Module 4 editing core).
// Pure data + operations, no Qt, no FFmpeg - unit tested in fc_timeline_tests.
// M4a owned placement, split, trim, and move; M4b adds cross-track moves
// with overlap rejection, magnetic drop resolution, ripple delete/trim,
// rolling boundary edits, and topmost-clip lookup for the program monitor.
// M5 Phase 2 adds cut transitions: every mutating operation preserves the
// transition invariants (adjacent pair, duration within the left clip) -
// broken pairs are dropped, shrunk left clips clamp the duration, and
// splitting the left clip re-targets the transition to the half that owns
// the cut. Multi-source compositing beyond topmost-wins and audio mixing
// arrive in later M5/M6 phases.
class TimelineModel {
public:
    TimelineModel() = default;

    void setFps(double fps);
    double fps() const { return fps_; }

    int addTrack(const std::string &name, bool isAudio);
    // M6 Phase 1: inserts a track at `position` (clamped to [0,
    // trackCount()]) and renumbers everything above it: every clip and
    // transition on a track with index >= position shifts up by one, and
    // all Track::index fields are rebuilt. Inserting at trackCount() is
    // exactly addTrack. A track cannot be both audio and text. Returns
    // the new track's index, or -1 on the audio+text contradiction.
    int insertTrack(int position, const std::string &name, bool isAudio, bool isText);
    int trackCount() const { return static_cast<int>(tracks_.size()); }
    const std::vector<Track> &tracks() const { return tracks_; }
    // Mutable lookup (model is non-const; e.g. setTrackState path).
    Track *trackAt(int index);
    // Const lookup - used by const views (TimelinePanel renders against a
    // const TimelineModel*). Required for const-correctness: callers on a
    // const model cannot bind to the non-const overload above.
    const Track *trackAt(int index) const;
    bool setTrackState(int index, bool locked, bool muted, bool solo);

    const std::vector<Clip> &clips() const { return clips_; }

    // Adds a clip; returns its id (>0) or 0 on invalid arguments.
    int64_t addClip(int trackIndex, const std::string &sourcePath, const std::string &label,
                    int64_t sourceInFrames, int64_t sourceOutFrames, int64_t timelineStart,
                    double rate = 1.0);

    // M6 Phase 1: adds a TEXT clip to a text track. The document is
    // normalized (empty runs dropped, adjacent equal styles merged, sizes
    // clamped); the label is derived from the text (textPreviewLabel).
    // Returns the clip id (>0), or 0 on invalid arguments: not a text
    // track, duration < 1, negative start, or overlap with another clip
    // on the track (text lanes are non-overlapping like every lane).
    // The clip has no source: sourcePath empty, sourceIn 0, sourceOut ==
    // durationFrames, rate 1.0 - all M4b mutators keep working (see the
    // Clip::text notes for the special cases).
    int64_t addTextClip(int trackIndex, const TextDocument &doc, int64_t timelineStart,
                        int64_t durationFrames);

    // M6 Phase 1: every text clip covering `frame`, in COMPOSITING order -
    // the bottom-most text lane FIRST, so higher text lanes (lower index,
    // drawn higher in the panel) paint on top. This is the paint list the
    // program monitor and the export walk after the video stack.
    std::vector<const Clip *> textClipsAt(int64_t frame) const;

    // M5 Phase 3 (project loading): the whole model is replaced in one
    // step by the project parser - tracks, clips (with PRESERVED ids +
    // effect stacks), transitions, and the fps; the id counter re-seeds
    // above the largest id seen. Used by fc::parseProject only; every
    // field is validated there before anything is moved in.
    void replaceAll(double fps, std::vector<Track> tracks, std::vector<Clip> clips,
                    std::vector<Transition> transitions);

    bool removeClip(int64_t id);

    // Splits every clip on `trackIndex` whose range contains `frame` (not at
    // a boundary) into two clips. Returns true if any clip was split.
    bool splitAt(int64_t frame, int trackIndex);

    bool moveClip(int64_t id, int64_t newTimelineStart);

    // M4b: move a clip to another track and/or position. Rejects invalid
    // track, negative start, kind mismatch (a clip on a video track cannot
    // move to an audio track and vice versa - clip kind is the kind of its
    // current track), and any overlap with another clip on the target
    // track. Use findDropPosition() first to get a guaranteed-valid start.
    bool moveClipTo(int64_t id, int newTrackIndex, int64_t newTimelineStart);

    // M4b: resolve the nearest valid drop start for a clip of the given
    // duration on the given track (the moving clip itself is excluded by
    // id so an in-place drop is always legal). Returns the start closest
    // to desiredStart that fits without overlapping anything; -1 when no
    // gap on the track can hold the clip or the target track is of the
    // wrong kind for the clip. "Magnetic": the desired position wins if
    // it is free, otherwise the result snaps to the nearest gap edge.
    int64_t findDropPosition(int trackIndex, int64_t clipId, int64_t desiredStart,
                             int64_t durationFrames) const;

    // Trim the start by `delta` timeline frames (positive = lose content
    // from the head, negative = extend). Source in-point and timeline start
    // move together. Honors sourceIn >= 0 and timelineStart >= 0.
    bool trimClipStart(int64_t id, int64_t deltaFrames);

    // Trim the end by `delta` timeline frames (positive = extend, negative =
    // shrink). Honors sourceOut > sourceIn.
    bool trimClipEnd(int64_t id, int64_t deltaFrames);

    // M4b ripple delete: remove the clip and shift every later clip on the
    // same track left by exactly its duration, closing the gap it leaves.
    bool rippleDelete(int64_t id);

    // M4b ripple trim end: trimClipEnd + shift every clip that started at
    // or after the trimmed clip's ORIGINAL end by the same delta (positive
    // delta pushes the following clips right, negative pulls them left).
    // The gap after the trimmed edge closes/opens; later gaps are kept.
    bool rippleTrimClipEnd(int64_t id, int64_t deltaFrames);

    // M4b rolling edit: move the shared boundary of two adjacent clips on
    // one track by `delta` timeline frames. The left clip's out-point and
    // the right clip's in-point + timeline start all shift by delta; the
    // total sequence length is unchanged. Rejects non-adjacent clips and
    // any delta that would collapse either clip to zero length or push the
    // right clip's source in-point negative.
    bool rollEdit(int64_t leftId, int64_t rightId, int64_t deltaFrames);

    const Clip *clipAt(int64_t frame, int trackIndex) const;
    Clip *clipById(int64_t id);
    // Const lookup for const views (findDropPosition resolves the moving
    // clip's kind from a const model).
    const Clip *clipById(int64_t id) const;

    // M4b: the clip the program monitor should show at a timeline frame -
    // the clip on the visually TOPMOST video lane that covers the frame
    // (video tracks are drawn bottom-up; track 0 is the topmost lane, so
    // the scan runs from index 0 downward). Returns nullptr in gaps.
    const Clip *activeVideoClipAt(int64_t frame) const;

    // ---- M5 Phase 2: cut transitions ----

    const std::vector<Transition> &transitions() const { return transitions_; }

    // Largest legal duration for a transition between the two clips (their
    // boundary must be adjacent, same video track, and free of an existing
    // transition); 0 when the pair cannot host one. Callers use this to
    // clamp UI defaults.
    int64_t maxTransitionDuration(int64_t leftClipId, int64_t rightClipId) const;

    // Places a transition on the shared boundary of the two clips. Returns
    // the transition id (> 0) or 0 when rejected: unknown clips, different
    // tracks, audio track, non-adjacent pair, unknown kind (the transitions
    // catalog must know it), an existing transition on that boundary, or
    // duration outside [1, maxTransitionDuration].
    int64_t addTransition(int64_t leftClipId, int64_t rightClipId, const std::string &kind,
                          int64_t durationFrames);

    bool removeTransition(int64_t id);

    // Re-validates the duration against the left clip's current extent;
    // rejects out-of-range values (the UI clamps before calling).
    bool setTransitionDuration(int64_t id, int64_t durationFrames);

    const Transition *transitionById(int64_t id) const;

    // The transition on the boundary of exactly these two clips, if any.
    const Transition *transitionBetween(int64_t leftClipId, int64_t rightClipId) const;

    // Resolves the transition sample covering `frame` on `trackIndex`
    // (the window [left end - duration, left end)); returns false when no
    // window covers the frame. The sample carries both source positions
    // the compositor needs (left LIVE, right HELD at its in-point).
    bool resolveTransitionAt(int64_t frame, int trackIndex, TransitionSample &out) const;

    int64_t durationFrames() const;
    double durationSeconds() const;

private:
    // Drops transitions whose pair broke (adjacency lost, clip removed,
    // moved away) and clamps durations that no longer fit the left clip.
    // Called at the end of every mutating operation.
    void pruneTransitions();

    double fps_ = 24.0;
    std::vector<Track> tracks_;
    std::vector<Clip> clips_;
    std::vector<Transition> transitions_;
    int64_t nextId_ = 1;
};

} // namespace fc
